name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
        
    - name: Test
      run: dotnet test
      
    - name: Publish
      run: dotnet publish src/Meziantou.Moneiz/Meziantou.Moneiz.csproj --configuration Release
    
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        # Set a generated GITHUB_TOKEN for pushing to the remote branch.
        # github_token: # optional
        publish_branch: gh-pages
        publish_dir: src/Meziantou.Moneiz/bin/Release/netstandard2.1/publish/wwwroot
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
